### ISSUE TITLE
Add @listen and @listenGesture

### ISSUE THREAD

**Issue by aomarks** [Polymer/polymer-decorators#14]
https://www.polymer-project.org/2.0/docs/devguide/events#imperative-listeners
https://www.polymer-project.org/2.0/docs/devguide/gesture-events

Since the `@listenGesture` decorator will need to call `Polymer.Gestures.addListener`, we'll need typings for the Polymer core globals. Once #9 is done (in progress), we'll have them. So we may want to wait until that is done before adding `@listenGesture`. We could also just use `as any` for now.

**Comment by aarondrabeck** [comment]
Sounds good! I will work on this and get a PR up.

**Comment by aomarks** [comment]
Fixed in #15
