### ISSUE TITLE
@property decorator fails with mixins

### ISSUE THREAD

**Issue by kito99** [Polymer/polymer-decorators#24]
Example:

```html
<link rel="import" href="../bower_components/polymer/polymer-element.html">
<link rel="import" href="../bower_components/polymer-decorators/polymer-decorators.html">
<link rel="import" href="../bower_components/app-localize-behavior/app-localize-behavior.html">
<dom-module id="my-view3">
  <template>
     <div></div>
  </template>
  <script src="my-view3.js"></script>
</dom-module>
```

```typescript
namespace App {
    const {customElement, property, query, queryAll, observe} = Polymer.decorators;
 
   @customElement('my-view3')
    class MyView3 extends Polymer.mixinBehaviors([(<any>Polymer).AppLocalizeBehavior], Polymer.Element) {
        @property()
        test: string;
    }
}
```

Stack trace:
```
caught TypeError: Cannot set property properties of class PolymerGenerated extends Base {

        static get properties() {
          return info.properties;
    ...<omitted>... } which has only a getter
    at global.js:53
    at DecorateProperty (Reflect.ts:1102)
    at Object.decorate (Reflect.ts:279)
    at __decorate (my-app.js:3)
    at App (my-view3.ts:9)
    at my-view3.ts:12
(anonymous) @ global.js:53
DecorateProperty @ Reflect.ts:1102
decorate @ Reflect.ts:279
__decorate @ my-app.js:3
App @ my-view3.ts:9
(anonymous) @ my-view3.ts:12
```

I haven't looked into this closely, but it looks like the decorator isn't taking into account properties added from the mixin.

**Comment by justinfagnani** [comment]
@kito99 I don't see decorators.ts on the stack trace, and also don't quite see how the property decorator could fail in a way to generate that error message. Here: https://github.com/Polymer/polymer-decorators/blob/master/src/decorators.ts#L73 there's a check for the own property, then an assignment to create it.

I wonder if `mixinBehaviors` returns a funky class that interferes with decoration in general? Do other decorators work?

**Comment by kito99** [comment]
@justinfagnani global.js is the compiled version of decorator.ts. I believe you're thoughts about `mixinBehaviors` are probably correct. I'm not sure what the execution order of the decorators is, so I don't know if other decorators are working first.

**Comment by 43081j** [comment]
its because of this [here](https://github.com/Polymer/polymer/blob/ee1d71f5f896ee57a0ee6d1f377ae6caa76e556b/lib/legacy/class.html#L146).

**Comment by justinfagnani** [comment]
Oh, I see...

This is a subtle interaction between accessors and properties, that's made more subtle by being static. The `hasOwnProperty` check returns false, because there is no property `properties`, there's an accessor instead. The assignment fails because there's a getter, but not setter.

The fix would be to replace the assignment with `Object.defineProperty(proto.constructor, 'properties', {value: {}})`.

Thanks @43081j!
