### ISSUE TITLE
@property does not take initialize value

### ISSUE THREAD

**Issue by yebrahim** [Polymer/polymer-decorators#31]
When using this decorator, can it also accept the initial value for the property, something like:

    @property({type: Boolean, value: false})
    propertyName: boolean;

Otherwise, is there a different way of specifying what the default initial value is?

**Comment by aomarks** [comment]
You can initialize the property using TypeScript like this:

```ts
@property({type: Boolean})
propertyName: boolean = false;
```

**Comment by yebrahim** [comment]
Is this the right way though?
If the property is assigned a value declaratively, which value does it end up with?

`<my-element prop1="true">`

**Comment by aomarks** [comment]
> Is this the right way though?
> If the property is assigned a value declaratively, which value does it end up with?
> 
> <my-element prop1="true">

In this example it will be "true". An external data binding wins over a TypeScript property initializer (which gets compiled to an assignment in the constructor) wins over a Polymer `value` option (which we don't allow from the decorator).

The fact that you need to use an initializer is now documented: https://github.com/Polymer/polymer-decorators#propertyoptions-propertyobjects
