### ISSUE TITLE
@computed reflectToAttribute

### ISSUE THREAD

**Issue by LarsDenBakker** [Polymer/polymer-decorators#34]
I have computed properties which need to reflect to attribute. If I understand it correctly, it is not supported currently.

**Comment by aomarks** [comment]
This should work:

```ts
@property({reflectToAttribute: true})
myProperty: string;
```

**Comment by aomarks** [comment]
Sorry, I just realized you were asking about computed properties. You can do this:

```ts
@property({computed: 'computeFoo(bar)', reflectToAttribute: true})
foo: number;

private computeFoo(bar: number) {
  return bar + 1;
}
```
