### ISSUE TITLE
polymer-decorators.d.ts file not included in the v1.0.1 release

### ISSUE THREAD

**Issue by davidrleonard** [Polymer/polymer-decorators#45]
The `polymer-decorators.d.ts` file is not included in the built files for v1.0.1. It was present in v1.0.0.

**Comment by aomarks** [comment]
> The polymer-decorators.d.ts file is not included in the built files for v1.0.1. It was present in v1.0.0.

My bad, releasing a fix now.

**Comment by aomarks** [comment]
Released v1.0.2 with the fix, sorry about that!
