### ISSUE TITLE
computed property without reflect type error

### ISSUE THREAD

**Issue by sebdoucet** [Polymer/polymer-decorators#65]
Hi,

This line produce an error that can't be worked arround without `Reflect` using `computed` properties:

https://github.com/Polymer/polymer-decorators/blob/0842e694c1995a0a59fed78f2ae3115fc7a26e2b/src/decorators.ts#L99

Cheers

**Comment by aomarks** [comment]
You're right, we should not show this warning for computed properties, because it is not actually important for computed properties to have a type (see https://github.com/Polymer/polymer-decorators/pull/51#issuecomment-368787769 for why).

A workaround for now is this:

```ts
@computed('foo')	
@property({type: String})	
get bar() { ... }
```

**Comment by sebdoucet** [comment]
Looking at the code and try it, don't seem to be an actual work arround.

**Comment by aomarks** [comment]
Hmm, I thought that would work. Which version are you on? It needs to be at least 1.1.0 for combining `@computed` and `@property` to work.

**Comment by sebdoucet** [comment]
Oh, ok, that's why.
