### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by robertop87** [Polymer/polymer-decorators#67]
When I build the polymer project I got
Uncaught TypeError: Cannot destructure property `customElement` of 'undefined' or 'null'.

**Comment by aomarks** [comment]
Hi @robertop87 -- we'll need some more information to act on this. Feel free to re-open if this is still an issue, and you have more details about your configuration so we can reproduce. You might also find the #typescript channel at https://polymer-slack.herokuapp.com/ helpful.
