### ISSUE TITLE
LitElement support

### ISSUE THREAD

**Issue by 43081j** [Polymer/polymer-decorators#69]
kinda related to #10.

How do we want to go about supporting LitElement in these decorators?

There's two paths really I guess:

* A single set of decorators, *some* of which work for both PolymerElement and LitElement
* A separate set of decorators (in this repo still, but specific to Lit)

From a user's point of view, I personally think they should be a single set because the internal behaviour isn't of much relevance to a user.

You would expect `@customElement` to register your element, whether it is PolymerElement or not. The only thing tying it into PolymerElement right now really is the use of `is`.

If we did want to achieve this, we could have a condition internally to check which kind of element we are trying to deal with. This can either be `(el: any) => el is LitElement` or the actual Lit types being depended on i suppose?

---

So summary:

* Do we want two decorators or one, to support these two element bases?
* Do we want to depend on Polymer and Lit, or do we want to have inline types?
* If we have one set of decorators, do we just throw an exception if the combination you try is unsupported? (`@observe` combined with a LitElement)

@justinfagnani  can you also post your lit decorators here, iirc they are modified copies of what is in this repo so could be a good start.

cc @justinfagnani @aomarks

**Comment by aomarks** [comment]
LitElement is going to vend its own decorators, follow https://github.com/Polymer/lit-element/issues/7
