### ISSUE TITLE
Bower install 2.1.0 returns ENOTFOUND

### ISSUE THREAD

**Issue by SketchBookkeeper** [Polymer/polymer-decorators#85]
**Output of `bower -v && npm -v && node -v`:**

```
1.8.8
6.13.4
v12.14.0
```

**Steps to reproduce the issue:**
1: `bower install polymer-decorators#2.1.0`

**Describe the results you received:**
```
bower polymer-decorators#2.1.0  cached https://github.com/Polymer/polymer-decorators.git#2.1.0
bower polymer-decorators#2.1.0         validate 2.1.0 against https://github.com/Polymer/polymer-decorators.git#2.1.0
bower                                 ENOTFOUND Package Polymer/polymer=Polymer/polymer not found
```

**Describe the results you expected:**
I ran this command on Dec 18th, 2019 and bower was able to install polymer-decorators. 

**Additional information:**
I wonder if it could be the way the dependencies are listed?
[bower.json](https://github.com/Polymer/polymer-decorators/blob/v2.1.0/bower.json)
```
  "dependencies": {
    "Polymer/polymer": "^2.4"
  }
```
As opposed to this :
```
  "dependencies": {
    "polymer": "polymer/polymer#^2.4.0"
  }
```
 Thank you!

**Comment by talshal3** [comment]
It still doesn't work for me, could you please check again? Thanks!

**Comment by SketchBookkeeper** [comment]
I noticed there is not a release with the changes from https://github.com/Polymer/polymer-decorators/pull/84. @talshal3 I think that is why it's still not working. I think we'll need to wait for a release, v2.1.1?

**Comment by SketchBookkeeper** [comment]
@aomarks Is the fix going to have a new release soon?

**Comment by aomarks** [comment]
Sorry for delay. I just tagged v2.1.1 for Bower, let me know if it fixes the problem.

**Comment by SketchBookkeeper** [comment]
I was able to install v2.1.1. Thank you so much!
