### ISSUE TITLE
Provide Polymer type declarations

### ISSUE THREAD

**Issue by aomarks** [Polymer/polymer-decorators#9]
We need to distribute a type declarations file for Polymer itself, so that TypeScript users can `extend Polymer.Element`. These decorators are not very usable without that piece.

Rather than distributing them with this decorators package, though, we'd prefer to work on https://github.com/Polymer/gen-typescript-declarations so that it can automatically generate typings for Polymer, and then start including those type declarations with the Polymer bower releases, so that a user can get the definitions for the `Polymer` namespace from e.g.:

`/// <reference path="../bower_components/polymer/polymer.d.ts" />`

**Comment by justinfagnani** [comment]
I think we can close this 😄
